In [1]:
import os
root_path = R'C:\Users\18779\Desktop\SummerCourse'
root_path_local = R'C:\Users\18779\Desktop\SummerCourse\北大法宝地方法规库批量下载2021.08.21. 12.05.11'
root_path_center = R'C:\Users\18779\Desktop\SummerCourse\北大法宝中央法规库批量下载2021.08.21. 12.07.31' 
root_path_local_list = os.listdir(root_path_local)
root_path_center_list = os.listdir(root_path_center)

In [35]:
import jieba
def solve(path_name_pairs):
    excludes = {} # 定义例外的词
    word_list = []
    for pair in path_name_pairs:
        root_path = pair[0]
        name_list = pair[1]
        print(root_path)
        for name in name_list:
            txt_name = name
            txt_path = os.path.join(root_path, txt_name)
            txt = open(txt_path, "r", encoding='utf-8').read()
            words = jieba.lcut(txt)
            word_list.append(words)

    counts = {}
    for words in word_list:
        for word in words:
            if len(word) == 1:  # 排除单个字符的分词结果
                continue
            else:
                counts[word] = counts.get(word, 0) + 1
        for word in excludes:
            del (counts[word])
    items = list(counts.items())
    items.sort(key=lambda x: x[1], reverse=True)
    freq_dict = {}
    word_list = []
    for i in range(10):
        word, count = items[i]
        word_list.append(word)
        freq_dict[word] = count
        print("{:*<10}{:->5}".format(word, count))
    return freq_dict, word_list

In [29]:
path_name_pairs = [[root_path_local, root_path_local_list], [root_path_center, root_path_center_list]]

In [37]:
excludes = {} # 定义例外的词
word_list = []
words_dict_list = []
for pair in path_name_pairs:
    root_path = pair[0]
    name_list = pair[1]
    print(root_path)
    for name in name_list:
        txt_name = name
        txt_path = os.path.join(root_path, txt_name)
        txt = open(txt_path, "r", encoding='utf-8').read()
        words = jieba.lcut(txt)
        word_list.append(words)

C:\Users\18779\Desktop\SummerCourse\北大法宝地方法规库批量下载2021.08.21. 12.05.11
C:\Users\18779\Desktop\SummerCourse\北大法宝中央法规库批量下载2021.08.21. 12.07.31


In [30]:
len(word_list)

9

In [14]:
for words in word_list:
    single_counts = {}
    for word in words:
        if len(word) == 1:  # 排除单个字符的分词结果
            continue
        else:
            single_counts[word] = single_counts.get(word, 0) + 1
    for word in excludes:
        del (single_counts[word])
    words_dict_list.append(single_counts)
# items = list(counts.items())
# items.sort(key=lambda x: x[1], reverse=True)
# freq_dict = {}
# for i in range(100):
#     word, count = items[i]
#     freq_dict[word] = count
#     # print("{:*<10}{:->5}".format(word, count))
# print(freq_dict)

In [36]:
f, w = solve(path_name_pairs)
print(w[:10])

C:\Users\18779\Desktop\SummerCourse\北大法宝地方法规库批量下载2021.08.21. 12.05.11
C:\Users\18779\Desktop\SummerCourse\北大法宝中央法规库批量下载2021.08.21. 12.07.31
美育********-9802
学校********-5154
艺术********-3786
课程********-2383
学生********-2139
教育********-2071
工作********-1988
教师********-1890
活动********-1615
发展********-1517
['美育', '学校', '艺术', '课程', '学生', '教育', '工作', '教师', '活动', '发展']


In [39]:
import numpy as np
num_keywords = 10
num_papers = len(root_path_local_list) + len(root_path_center_list)
print(num_papers)
key_words_list = w[:10]
word_mat = np.zeros((10, num_papers))
len(words_dict_list)

96


0

In [25]:
for i in range(num_papers):
    tem_word_dict = words_dict_list[i]
    for j, keyword in enumerate(key_words_list):
        if keyword in tem_word_dict.keys():
            word_mat[j, i] = tem_word_dict[keyword]
print(word_mat)

[[ 81.  40.  21.  11.  42.  36.  20.   9.  28.]
 [ 72.   0.  21.  51.  16.  22.   0.   0.   0.]
 [ 38.  17.   1.  58.   6.  16.  16.   0.  11.]
 [ 66.   9.   3.  68.   1.   5.   0.   1.   6.]
 [  2.  47.   0.   2.  42.  43.   0.   1.   2.]
 [  0.   0.   0. 101.   0.   0.   0.   0.   0.]
 [ 27.   7.   9.   3.   7.  13.   7.   3.  11.]
 [ 13.  33.   1.   4.  17.   6.   2.   9.   1.]
 [ 11.   7.   9.   0.   4.   8.  16.   0.  22.]
 [ 26.   4.   0.  17.   1.   5.   5.   0.  10.]]


In [27]:
np.sum(word_mat, axis=1)

array([288., 182., 163., 159., 139., 101.,  87.,  86.,  77.,  68.])

In [28]:
np.savetxt('word_mat.csv', word_mat,delimiter=',')