In [121]:
import os
root_path = R'C:\Users\zgj_t\Desktop\SummerCourse'
root_path_local = R'C:\Users\zgj_t\Desktop\SummerCourse\北大法宝地方法规库批量下载2021.08.21. 12.05.11'
root_path_center = R'C:\Users\zgj_t\Desktop\SummerCourse\北大法宝中央法规库批量下载2021.08.21. 12.07.31' 
root_path_local_list = os.listdir(root_path_local)
root_path_center_list = os.listdir(root_path_center)

In [137]:
import numpy as np
path_name_pairs = [[root_path_center, root_path_center_list]]
num_keywords = 15
num_papers = len(root_path_center_list)
excludes = {} # 定义例外的词

In [138]:
root_path_center_list

['中共中央办公厅、国务院办公厅印发《关于全面加强和改进新时代学校美育工作的意见》(FBM-CLI-16-346926).txt',
 '国务院办公厅关于全面加强和改进学校美育工作的意见(FBM-CLI-2-257676).txt',
 '教育部关于切实加强新时代高等学校美育工作的意见(FBM-CLI-4-331212).txt',
 '教育部关于印发《学校体育美育兼职教师管理办法》的通知(FBM-CLI-4-304424).txt',
 '教育部关于成立首届全国高校美育教学指导委员会的通知(FBM-CLI-4-345235).txt',
 '教育部关于推进学校艺术教育发展的若干意见(FBM-CLI-4-217726).txt',
 '教育部办公厅关于举办全国第三届高校艺术教育科研论文报告会和全国大学校长美育论坛的通知(FBM-CLI-4-146351).txt',
 '教育部办公厅关于公布体育美育浸润行动计划入选名单的通知(FBM-CLI-4-337360).txt',
 '教育部办公厅关于开展体育美育浸润行动计划的通知(FBM-CLI-4-333470).txt',
 '教育部办公厅关于成立首届全国中小学美育教学指导专业委员会的通知(FBM-CLI-4-354375).txt',
 '教育部办公厅关于签署第一批学校美育改革发展备忘录有关事项的通知(FBM-CLI-4-278235).txt',
 '教育部办公厅关于遴选首届全国中小学美育教学指导专业委员会委员人选的通知(FBM-CLI-4-351357).txt']

In [139]:
import jieba
def solve(path_name_pairs):
    full_word_list = []
    for pair in path_name_pairs:
        root_path = pair[0]
        name_list = pair[1]
        print(root_path)
        for name in name_list:
            txt_name = name
            txt_path = os.path.join(root_path, txt_name)
            txt = open(txt_path, "r", encoding='utf-8').read()
            words = jieba.lcut(txt)
            full_word_list.append(words)

    counts = {}
    for words in full_word_list:
        for word in words:
            if len(word) == 1 or (word in excludes):  # 排除单个字符的分词结果
                continue
            else:
                counts[word] = counts.get(word, 0) + 1
    items = list(counts.items())
    items.sort(key=lambda x: x[1], reverse=True)
    freq_dict = {}
    word_list = []
    for i in range(num_keywords*10):
        word, count = items[i]
        word_list.append(word)
        freq_dict[word] = count
        print("{:*<10}{:->5}".format(word, count))
    return full_word_list, freq_dict, word_list

In [140]:
full_word_list, f, w = solve(path_name_pairs)

C:\Users\zgj_t\Desktop\SummerCourse\北大法宝中央法规库批量下载2021.08.21. 12.07.31
美育********--524
艺术********--396
教育********--299
学校********--265
高校********--202
工作********--124
发展********--121
学生********--115
课程********--114
教学********--110
教师********--105
论文********--101
建设********---99
专业********---82
活动********---79
教育部*******---72
文化********---69
中小学*******---68
全国********---66
研究********---66
实践********---63
开展********---58
社会********---57
指导********---53
中小学校******---53
推进********---52
机制********---48
改革********---47
建立********---45
培养********---44
支持********---44
全面********---43
鼓励********---43
关于********---42
组织********---42
服务********---42
兼职教师******---38
纳入********---37
创新********---36
评价********---35
行政部门******---35
坚持********---34
审美********---33
资源********---33
报告会*******---32
育人********---31
公共********---31
各级********---30
高等学校******---30
提高********---29
管理********---29
各地********---29
行动计划******---29
强化********---28
具有********---28
相关********---28
制度********---28
报送********---28
要求

In [141]:
words_dict_list = []
for words in full_word_list:
    single_counts = {}
    for word in words:
        if len(word) == 1 or (word in excludes):  # 排除单个字符的分词结果
            continue
        else:
            single_counts[word] = single_counts.get(word, 0) + 1
    words_dict_list.append(single_counts)
len(words_dict_list)

12

In [142]:
key_words_list = w[:num_keywords]
key_words_list

['美育',
 '艺术',
 '教育',
 '学校',
 '高校',
 '工作',
 '发展',
 '学生',
 '课程',
 '教学',
 '教师',
 '论文',
 '建设',
 '专业',
 '活动']

In [143]:
word_mat = np.zeros((num_keywords, num_papers))
for i in range(num_papers):
    tem_word_dict = words_dict_list[i]
    for j, keyword in enumerate(key_words_list):
        if keyword in tem_word_dict.keys():
            word_mat[j, i] = tem_word_dict[keyword]
print(word_mat)

[[ 87. 146.  81.  40.  21.   3.  11.  42.  36.  20.   9.  28.]
 [ 57.  38.  66.   9.   3. 142.  68.   1.   5.   0.   1.   6.]
 [ 24.  26.  38.  17.   1.  86.  58.   6.  16.  16.   0.  11.]
 [ 59.  62.  13.  33.   1.  58.   4.  17.   6.   2.   9.   1.]
 [ 11.   8.  72.   0.  21.   1.  51.  16.  22.   0.   0.   0.]
 [ 15.  16.  27.   7.   9.   6.   3.   7.  13.   7.   3.  11.]
 [ 14.  30.  18.   7.   0.  20.   8.   3.  11.   2.   8.   0.]
 [ 20.  28.  13.  10.   0.  28.   2.   3.  11.   0.   0.   0.]
 [ 26.  34.  14.   2.   1.  19.   4.   3.   9.   1.   0.   1.]
 [ 13.  13.  11.   7.   9.   7.   0.   4.   8.  16.   0.  22.]
 [ 17.  21.  13.   6.   1.  15.  17.   3.   5.   5.   0.   2.]
 [  0.   0.   0.   0.   0.   0. 101.   0.   0.   0.   0.   0.]
 [ 18.  16.  21.   6.   2.   6.   9.   7.   8.   2.   0.   4.]
 [  4.   9.  26.   4.   0.   1.  17.   1.   5.   5.   0.  10.]
 [ 10.  13.  11.   3.   0.  16.  13.   3.  10.   0.   0.   0.]]


In [144]:
np.sum(word_mat, axis=1)

array([524., 396., 299., 265., 202., 124., 121., 115., 114., 110., 105.,
       101.,  99.,  82.,  79.])

In [145]:
np.savetxt('word_mat.csv', word_mat,delimiter=',')